language: node_js
node_js:
  - node
script:
  - yarn run lint
  - yarn run unused
branches:
  only:
    - master
cache:
  yarn: true
notifications:
  slack:
    secure: zcHEe8Un82j/eD/lUB0dToQmt7PSwGvKRYg8riSTy79vwVQuz7su2F0xInU15+Gtfz71h4B+bXbFaqiSemI6Xfv/Zu7pcPyn9+n0FK/wSadffa18PMASaArqLOiV8Sy8vCSSHipqns1QqNbqP0gawKN/Xxqr5AYYa15CauxSmlqFQNsGnQlrEPEkJD7FQKQ2uus57Vj98FAmZAN0yFXdu5uoKgzV7qtmMyfeVHVfOVznOj7WJyWPMoPBWrqyKtjSpAxVoED7ngIRlQPJzwq9IKZn2xIlCp8EgSJQCC27qctJETW1QsKIQasEvSJ7gstFDhJS/IBGNMhSESoRjI0Yxw1wtZrV9sxe6Fi00MoYGuLzyW3Wb5vuNE4hWNHWeUIUFDHQhUAWWJ8CAidsCTj4Y4IjcHRqzAQkknaPoEWQFPQfKDIqWfXSfXHQDBMIA0DDe8ZdL1u8sdbQ2DbvVTxwycjxocunB94aGDVuO9kH39D288BPqBn9Lz1Wrnese1kv12/jRXtpX7r2ApLbtSdSVMLhOKIwYWYJKx/ATIBMS0luNP6rKwJ/gI6wiEE25964+p8pEJC/MOC6/4zdt8SGgw0Q61/dYBxxwct/fZQ1BRaTv4yZzkaoqXU0E6s/Ve6cbN7hSRLTTuSbzgJR7gp1XvI0TP84ZHw0+UnDWGAQiWE=
deploy:
  provider: npm
  email: m.priver@gmail.com
  api_key:
    secure: BEST8sYy7VCElnpY8vxqg1/jSFQnedu4ntxVvtlAGCXjfhh2bMBoqc5wN1yC3LEEP4CDVjzT8tJ/bSInzpnwX5aiHXt6gN+YgH1Vny2KLHPYjE7LtlHBvunmxyALyGfR/ifsJRw4PF8Gik6bOCwNJiNssj5vS28GDnObhliSC5EFRUVbj5T8LWSG1rPJAjpqOFtugGMuZzjYJT86IU48KVcJ6numEI20mtMyElwjWDLw2OrecsjIeYWjD6CbBFL8WgeAzLciBbKc4IUpUzhtC9O1+6Kcs4fKFzvRg5YkgRAukIDq+mj8P2k2fzJTPel0mG8LoAybBFWmIpnpIViSqkIx1CEP5PhxUjR77seAwdQun+CcAhwOG40PVG759vb4wSJ6YBST9jzdGf80g7lFjSbeh3KJPLBa2g7nDugLG+yaXJ7a80xn+7Fgm+yPUT5jwFVP/roaNTQ+8QJ0izjMqEE0bOMGXu69oK49RJm3LZH/fI/ye65D/At+ZMgn6Dbg1Y/56vI/2JHh2Ib8SAEOelfVKa6L26wqkkAs70otvE1etrV5xqNqBjQ/W0+hTjQ3puSiBE8YTw3xpqrdwa0Kg+G0HdZYXjQEzBxZIoh6k3gcyE/B9SzYQcdtYhVsbt5IYrIBoCW8SLsXGJnfWRN9BkUmIw7xv68+yLBOEPkb2Dk=
  on:
    tags: true
    repo: priver/eslint-config-priver
    branch: master
